const names = [
  "Marla Paez",
  "Claudio Feathers",
  "John Shute",
  "Bernarda Sea",
  "Callie Leist",
  "Mckinley Stamm",
  "Arnold Hoke",
  "May Berry",
  "Corey Neeson",
  "Daphine Launer",
  "Manuel Goetzinger",
  "Bruno Freitas",
  "Marty Stiff",
  "Rudolph Shoaff",
  "Clyde Vigliotti",
  "Jong Dirks",
  "Ivory Kelso",
  "Stanley Forsberg",
  "Charmain Brousseau",
  "Cristina Brazil",
  "Jeramy Jackson",
  "Madlyn Krogh",
  "Emily Popham",
  "Talia Comacho",
  "Lovella Bolan",
  "Aleida Feaster",
  "Shyla Adamek",
  "Alton Laster",
  "Bethel Wickstrom",
  "Rebecka Hedgpeth",
  "Lavenia Herron",
  "Lisa Fill",
  "Desire Joyner",
  "Altha Maxim",
  "Fallon Lafrance",
  "Cletus Simpkins",
  "Edgardo Mosteller",
  "Lorelei Fugitt",
  "Elsa Acklin",
  "Cristin Knepper",
  "Mose Larger",
  "Christia Gwynn",
  "Zelma Bruggeman",
  "Angelo Westbrooks",
  "Kelvin Miland",
  "Kennith Degree",
  "Dotty Updike",
  "Raleigh Barksdale",
  "Dania Provence",
  "Reanna Opp",
]


/**
 * @return - [{name: 'Some Name', key: 0}, ..]
 */
export const getNames = () => {
  return names.map((name, key) => ({name, key}));
}